# Generated by Django 4.1 on 2023-02-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
