# Generated by Django 4.1 on 2022-11-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(max_length=25, null=True)),
                ('desc', models.CharField(max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.IntegerField(null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
