# Generated by Django 4.1 on 2023-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_change_allowerd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
