# Generated by Django 4.1 on 2023-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_user_username_change_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_allowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
