# Generated by Django 4.1 on 2022-11-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('computer ', 'Komputery i akcesoria'), ('books', 'Książki'), ('clothes', 'Odzież, obuwie i akcesoria')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
