# Generated by Django 4.1 on 2022-11-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_remove_product_category_alter_category_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=140, null=True)),
                ('model', models.CharField(max_length=140, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.category')),
            ],
        ),
    ]
