# Generated by Django 4.1 on 2022-11-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_subcategory_delete_keyboards_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
