# Generated by Django 4.1 on 2022-11-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
