# Generated by Django 4.1 on 2022-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('computer ', 'Komputery i akcesoria'), ('books', 'Książki'), ('clothes', 'Odzież, obuwie i akcesoria')], max_length=50, null=True),
        ),
    ]
