# Generated by Django 4.1 on 2022-11-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_remove_product_url_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
    ]
