# Generated by Django 4.1 on 2022-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_remove_product_url_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image_url',
            field=models.TextField(null=True),
        ),
    ]
