# Generated by Django 4.1 on 2022-11-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_rename_image_product_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_image_url',
        ),
    ]
