# Generated by Django 4.1 on 2022-11-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_remove_product_item_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_image',
            new_name='image',
        ),
    ]
