# Generated by Django 4.1 on 2022-11-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0042_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
