# Generated by Django 4.1 on 2022-11-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0048_remove_card_user_having_user_card_alter_card_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='product',
            new_name='product_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
