# Generated by Django 4.1 on 2022-11-25 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0050_remove_card_product_list_remove_card_user_card_xdd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='xdd',
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='products',
            field=models.ManyToManyField(blank=True, to='frontend.product'),
        ),
    ]
