# Generated by Django 4.1 on 2022-11-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0051_remove_card_xdd_card_owner_card_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
    ]
