# Generated by Django 4.1 on 2022-11-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0052_rename_card_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
