# Generated by Django 4.1 on 2022-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0054_remove_cart_owner_remove_cart_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='test',
            name='products',
            field=models.ManyToManyField(blank=True, to='frontend.product'),
        ),
    ]
