# Generated by Django 4.1 on 2022-11-25 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0055_delete_cart_test_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
