# Generated by Django 4.1 on 2022-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0056_test_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='frontend.product'),
        ),
    ]
