# Generated by Django 4.1 on 2022-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0057_alter_test_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('elektronika', 'Elektronika'), ('książki', 'Książki'), ('instrumenty muzyczne', 'Instrumenty muzyczne'), ('dom i kuchnia', 'Dom i kuchnia')], max_length=50, null=True),
        ),
    ]
