# Generated by Django 4.1 on 2022-12-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0059_alter_user_coins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Cart',
        ),
    ]
