# Generated by Django 4.1 on 2022-12-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0061_rating_product_rating_of_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_of_product',
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.product'),
        ),
    ]
