# Generated by Django 4.1 on 2022-12-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_rating',
        ),
    ]
