# Generated by Django 4.1 on 2022-12-28 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0063_remove_rating_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated_product',
        ),
        migrations.AddField(
            model_name='product',
            name='rated_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.rating'),
        ),
    ]
