# Generated by Django 4.1 on 2022-12-28 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0064_remove_rating_rated_product_product_rated_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='average_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rated_product',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='number_of_ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.product'),
        ),
    ]
