# Generated by Django 4.1 on 2022-12-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0065_rename_rating_rating_average_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='average_rate',
            new_name='rate',
        ),
    ]
