# Generated by Django 4.1 on 2022-12-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0066_rename_average_rate_rating_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='UserRate',
        ),
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('average_rate', models.ManyToManyField(blank=True, null=True, to='frontend.userrate')),
            ],
        ),
    ]
