# Generated by Django 4.1 on 2022-12-28 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0067_rename_rating_userrate_averagerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrate',
            name='rated_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.product'),
        ),
    ]
