# Generated by Django 4.1 on 2022-12-28 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0068_alter_userrate_rated_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrate',
            old_name='rated_product',
            new_name='rated_products',
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='result',
        ),
        migrations.AddField(
            model_name='averagerating',
            name='rated_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.product'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='average_rate',
            field=models.ManyToManyField(blank=True, to='frontend.userrate'),
        ),
    ]
