# Generated by Django 4.1 on 2022-12-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0069_rename_rated_product_userrate_rated_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AverageRating',
        ),
    ]
