# Generated by Django 4.1 on 2022-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0070_delete_averagerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
