# Generated by Django 4.1 on 2023-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0072_alter_userrate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
