apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      containers:
      - name: beat-container
        image: x03xd/amazon_clone:celery
        ports:
          - containerPort: 8100
        command: ["celery"]
        args: ["-A", "amazon", "beat", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: amqp-host
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: celery-result-backend
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: django_settings_module
---
apiVersion: v1
kind: Service
metadata:
  name: beat-service
spec:
  selector:
    app: beat
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 8100