# Generated by Django 4.1 on 2023-07-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
