# Generated by Django 4.1 on 2022-10-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
