# Generated by Django 4.1 on 2023-07-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0006_cartitem_remove_cart_products_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='amazonApp.cart'),
        ),
    ]
