# Generated by Django 4.2.4 on 2023-09-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0041_alter_opinion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonApp.rate'),
        ),
    ]
